services:
  # nginx
  web:
    build:
      context: ./client
      target: production
    ports:
      - 9000:80  
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always  
  api:
    build:
      context: ./api
    container_name: backend
    # volumes:
    #   - ./app:/app
    volumes:
      - /var/www/html/vendor
      - ./app:/var/www/html

  db:
    image: postgres
    container_name: DB
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: scopic
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: