version: "3.8"
services:
  dev-db:
    image: postgres
    container_name: nest-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: scopic
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
